### PR TITLE
Allow `transformers-0.6`

### LINKED ISSUE #30: Allow building with `transformers-0.6.*`
As far as I can tell, the upper version bounds can be lifted without any other changes:

```diff
diff --git a/microstache.cabal b/microstache.cabal
index daa4ec2..e225db6 100644
--- a/microstache.cabal
+++ b/microstache.cabal
@@ -57,7 +57,7 @@ library
     , filepath              >=1.3.0.0 && <1.5
     , parsec                >=3.1.11  && <3.2
     , text                  >=1.2     && <1.3
-    , transformers          >=0.3.0.0 && <0.6
+    , transformers          >=0.3.0.0 && <0.7
     , unordered-containers  >=0.2.5   && <0.3
     , vector                >=0.11    && <0.13
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #30.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
The [GHC 7.4.2 build fails](https://github.com/haskellari/microstache/runs/6434564837?check_suite_focus=true), surprisingly enough:

```
[2 of 5] Compiling Text.Microstache.Parser ( src/Text/Microstache/Parser.hs, /__w/microstache/microstache/dist-newstyle/build/x86_64-linux/ghc-7.4.2/microstache-1.0.2/build/Text/Microstache/Parser.o )

src/Text/Microstache/Parser.hs:44:28:
    Couldn't match expected type `mtl-1.1.1.1:Control.Monad.Identity.Identity'
                with actual type `Identity'
    Expected type: Parsec Text Delimiters [Node]
      Actual type: Parser [Node]
    In the return type of a call of `pMustache'
    In the first argument of `runParser', namely `(pMustache eof)'
```

This is because the build plan chooses `mtl-1.1.1.1`, in which [`Control.Monad.Identity` redefines its own version of `Identity`](https://hackage.haskell.org/package/mtl-1.1.1.1/docs/Control-Monad-Identity.html), separate from the `Identity` in `transformers`.

@phadej, would you be OK with raising the lower version bounds on `mtl` to `>= 2`? `mtl-2.0.0.0` and later re-export `Identity`, so I don't believe that should pose any challenges.

**Comment by phadej** [comment]
@RyanGlScott microstache doesn't depend on `mtl`.

Latest `parsec` has `mtl >=2.1.3.1` lower bound, but requiring that would rule out bundled ones on recent GHCs.

**Comment by phadej** [comment]
A small code change fixes that. I'll push it as soon as my local test passes

**Comment by phadej** [comment]
https://hackage.haskell.org/package/microstache-1.0.2.1 published

**Pull request merged**
